### ISSUE TITLE
Weird spacing between UITextView and Keyboard

### ISSUE THREAD

**Issue by codepushr** [JRG-Developer/AutoLayoutTextViews#3] opened 2015-11-23 14:02 UTC
Hi there,

thanks for the library! I'm using `ALKeyboardAvoidingTextView` and sadly I got a problem, everything works well (when the keyboard appears it resizes the TextView) except that there is a weird ~40pixel spacing between my UITextView and Keyboard.

First I thought maybe its the `inputAccessoryView` of the UITextField but after checking (setting it to nil) I found out that it has to be the bottom constraint that fools around.

Any ideas? (Using iOS 9.1 and Xcode 7.1.1)

<img src="http://i.imgur.com/E1POpFs.jpg" />

**Comment by JRG-Developer** [comment] 2016-11-22 15:49
I'm not able to reproduce this.

This ticket is fairly old, however, so it's likely this isn't a problem anymore...?

I'm closing this ticket for now...

If you're still having issues, please provide a link to a demo project and/or PR, and I'd be happy to re-open this.

**Closed by JRG-Developer** 2016-11-22 15:49 UTC
